# Generated by Django 5.1.1 on 2024-10-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(),
        ),
    ]
