# Generated by Django 5.1.1 on 2024-10-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='tmdb_id',
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
