# Generated by Django 5.1.1 on 2024-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtimes',
            name='theatre',
        ),
        migrations.AddField(
            model_name='showtimes',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
