# Generated by Django 5.1.1 on 2024-10-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.TextField(default='path/to/default/poster.jpg'),
        ),
    ]
